### ISSUE TITLE
API methods for individual solutions

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-slave#4]
We need a method that (re-)processes a solution by ID. Something like

`api/process/by/id/<uuid>`

**Comment by 5cript** [comment]
pdfs cannot yet be created anew, if they already exist.
Although one may use the reset function.

**Comment by 5cript** [comment]
Explicitly processing an already processed solution by id will now reset it first.
Therefore a manual reset is not needed anymore.
